config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :users, through: :chat_room_users
  has_many :chat_messages
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room, optional: true
  belongs_to :user, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  validates :user_id, uniqueness: { scope: :post_image_id }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image

  def liked_by(user)
    # user_idとpost_image_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_image_id: id)
  end

  # has_many :likes, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  validates :user_id, uniqueness: { scope: :image_id }

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  attachment :profile_image

  has_many :likes
  has_many :comments
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_action :authenticate_user!,except: [:top, :public_action]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    post_images_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to action: :show, id: chat_room.id
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @chat_room_user = @chat_room.chat_room_users.where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: @chat_room)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @post_image = @comment.post_image
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post_image = @comment.post_image
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.required(:comment).permit(:user_id, :post_image_id, :comment)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    @like = current_user.likes.new(like_params)
    @like.save
  end


  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    @like = Like.find_by(id: params[:id])
    @like.destroy
  end

  private
    def like_params
      params.permit(:post_image_id)
    end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
    @user = current_user
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
       redirect_to post_images_path
    else
       @post_images = PostImage.limit(10).order('created_at DESC')
       render :index
    end
  end

  def index
    @post_images = PostImage.limit(10).order('created_at DESC')
  end

  def show
    @post_image = PostImage.find(params[:id])
    @user = @post_image.user
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/show.html.erb
<p>チャットルームページ</p>
<div id='chat-messages'>
    <%= render @chat_messages %>
</div>

<form class="chat-room__message-form">
  <textarea data-behavior="chat_room_speaker" data-chat_room_id="<%= @chat_room.id %>" placeholder="メッセージを入力" class="chat-room__message-form_textarea"></textarea>
</form>

app/views/comments/create.js.erb
$('#comment-post-<%= @post_image.id.to_s %>').
  html('<%= j render "post_images/comment_list", { post: @post_image } %>');
$('#comment-form-post-<%= @post_image.id.to_s %> #comment_comment').val("");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post_image.id.to_s %>').
  html('<%= j render "post_images/comment_list", { post: @post_image } %>');

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="logo">
            <h2>EcoHabigram</h2>
            <p class="text-secondary">エコハビメンバーの写真や動画をチェックしよう</p>
          </div>
          <%= form_with model: User.new, url: new_user_session_path, local: true do |f| %>
                <!--<div class="form-group">-->
                <!--  <%#= f.email_field :email, autofocus: true, placeholder: "メールアドレス", class: "form-control" %>-->
                <!--</div>-->

            <div class="form-group">
              <%= f.label :name %><br />
              <%= f.text_field :name, autofocus: true, placeholder: "25th 真田隼輔", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", placeholder: "パスワード", class: "form-control" %>
            </div>

                <!--<div class="form-group">-->
                  <%#= f.password_field :password_confirmation, autocomplete: "off", placeholder: "パスワードの確認", class: "form-control" %>
                <!--</div>-->

            <div class="actions">
              <%= f.submit "ログイン", class: "btn btn-primary w-100" %>
            </div>
            <% end %>

            <br>

            <p class="devise-link">
              初めてのユーザーは
              <%= link_to "新規登録", new_user_registration_path %>
            </p>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post_image.id.to_s %>').
  html('<%= link_to "", post_image_like_path(@post_image.id, @like), method: :DELETE, remote: true, class:"fas fa-heart", style:"color: red; font-size: 2.0em;" %>');
<!--$('#like-icon-post-<%#= @post_image.id.to_s %>').-->
  <!--html('<i class="far fa-comment"></i>');-->
$('#like-text-post-<%= @post_image.id.to_s %>').
  html('<%= j render "post_images/like_text", { likes: @post_image.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post_image.id.to_s %>').
  html('<%= link_to "", post_image_likes_path(@post_image), method: :POST, remote: true, class:"far fa-heart", style:"font-size: 2.0em;" %>');
<!--$('#like-icon-post-<%#= @post_image.id.to_s %>').-->
  <!--html('<i class="far fa-comment"></i>');-->
$('#like-text-post-<%= @post_image.id.to_s %>').
  html('<%= j render "post_images/like_text", { likes: @post_image.likes } %>');

app/views/post_images/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-11">
      <span>
        <strong>
          <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
        </strong>
      </span>
      <span><%= comment.comment %></span>
    </div>
    <div class="col-md-1">
      <% if comment.user == current_user %>
        <%= link_to "", post_image_comment_path(post.id, comment), method: :delete, remote: true, class: "fas fa-times" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/post_images/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/post_images/index.html.erb
<% @post_images.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= attachment_image_tag post.user, :profile_image ,fallback: "icon.png" ,size:'50x50'%>
          <% end %>
          <%= link_to user_path(post.user), class: "user black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>
        </div>
        <span class="resize-image">
          <%= link_to post_image_path(post.id) do %>
            <%= attachment_image_tag post, :image %>
        <% end %>
        </span>
        <div class="card-body">
          <div class="row parts">
            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "", post_image_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class:"fas fa-heart", style:"color: red; font-size: 2.0em;" %>
                <!--<i class="far fa-comment"></i>-->
                <!--<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>-->
              <% else %>
                <%= link_to "", post_image_likes_path(post), method: :POST, remote: true, class:"far fa-heart", style:"font-size: 2.0em;" %>
                <!--<i class="far fa-comment"></i>-->
                <!--<i class="far fa-heart" aria-hidden="true"></i>-->
              <% end %>
            </div>
            <%#= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
            <span><strong><%= post.user.name %></strong></span><br>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_image_path(post), class: "post-time no-text-decoration" %>
            <hr>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%#= link_to time_ago_in_words(post.created_at).upcase + "前", post_image_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <div class="col-md-10">
                <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.hidden_field :post_image_id, value: post.id %>
                  <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメントを追加 ...", autocomplete: :off %>
              </div>
              <div class="col-md-2">
                  <%= f.submit "コメント投稿", class:"btn btn-info" %>
              </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/post_images/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post_image, class: "upload-images p-0 border-0" do |f| %>

          <div class="mb-3">
            <%= f.attachment_field :image %>
          </div>
          <div class="form-group row mt-2">
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
            </div>
          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <span class="resize-image">
          <%= attachment_image_tag @post_image, :image %>
        </span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@user), class: "no-text-decoration" do %>
              <%= attachment_image_tag @user, :profile_image ,fallback: "icon.png" ,size:'50x50'%>
            <% end %>
            <%= link_to user_path(@user), class: "black-color no-text-decoration post-user-name",
              title: @user.name do %>
              <strong><%= @user.name %></strong>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post_image.caption %>
            </strong>
          </div>
          <hr>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post_image.id.to_s %>">
                <%= render 'comment_list', post: @post_image %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post_image.id.to_s %>">
            <% if @post_image.liked_by(current_user).present? %>
              <%= link_to "", post_image_like_path(@post_image.id, @post_image.liked_by(current_user)), method: :DELETE, remote: true, class:"fas fa-heart", style:"color: red; font-size: 2.0em;" %>
              <!--<i class="far fa-comment"></i>-->
              <!--<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>-->
            <% else %>
              <%= link_to "", post_image_likes_path(@post_image), method: :POST, remote: true, class:"far fa-heart", style:"font-size: 2.0em;" %>
              <!--<i class="far fa-comment"></i>-->
              <!--<i class="far fa-heart" aria-hidden="true"></i>-->
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @post_image.id.to_s %>">
          <%= render "like_text", { likes: @post_image.likes } %>
        </div>
        <div class="post-time"><%= time_ago_in_words(@post_image.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @post_image.id.to_s %>">
          <div class="col-md-10">
            <%= form_with model: [@post_image, Comment.new], class: "w-100" do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_image_id, value: @post_image.id %>
              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメントを追加 ...", autocomplete: :off %>
          </div>
          <div class="col-md-2">
              <%= f.submit "投稿", class:"btn btn-info" %>
          </div>
            <% end %>
        </div>
        <hr>
        <% if @post_image.user == current_user %>
          <%= link_to "投稿の削除", post_image_path(@post_image), method: :delete, class:"btn btn-danger"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User Info</h2>
      <div class="form-body p-4">
        <%# if @user.errors.any? %>
          <%# @user.errors.full_messages.each do |message| %>
            <%#= message %>
          <%# end %>
        <%# end %>
        <%= form_with model: @user, local:true do |f| %>
          <div class="input-group mb-3 mt-4">
            <div class="form-group">
              <label for="user_name">Name</label>
              <%= f.text_field :name, class:"form-control" %>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.attachment_field :profile_image, class: "w-100" %>
            </div>
            <div class="form-group">
              <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction, class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-lg btn-block btn-info mt-4" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="matching">
    <p class="matching-title ml-3">メッセージ</p>
    <div class="matching__list">
      <% unless @users.empty? %>
        <% @users.each do |user| %>
        <%= link_to chat_rooms_path(params: { user_id: user.id }), method: :post do %>
         <div class="matching__person">
             <%= attachment_image_tag @user, :profile_image ,fallback: "icon.png" ,size:'150x150', class: "round-img" %>
           <div class="matching__person-name">
             <%= user.name %>
           </div>
         </div>
         <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
      <div class="col-md-5 text-right">
        <%= attachment_image_tag @user, :profile_image ,fallback: "icon.png" ,size:'150x150', class: "round-img" %>
      </div>
      <div class="col-md-7 text-center">
        <div class="row">
          <h1><%= @user.name %></h1>
          <%= link_to "Edit Profile", edit_user_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        </div>
        <div class="row">
          <p><%= @user.introduction %></p>
        </div>
        <% if @user == current_user %>
          <div class="row">
            <p>
              <%= @user.email %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="flex-box">
    <% @post_images.each do |post_image| %>
      <%= link_to post_image_path(post_image.id) do %>
        <%= attachment_image_tag post_image, :image ,size:'300x300' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>