config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :users, through: :chat_room_users
  has_many :chat_messages
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room, optional: true
  belongs_to :user, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  validates :user_id, uniqueness: { scope: :post_image_id }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image

  def liked_by(user)
    # user_idとpost_image_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_image_id: id)
  end

  # has_many :likes, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  validates :user_id, uniqueness: { scope: :image_id }

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  attachment :profile_image

  has_many :likes
  has_many :comments
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to action: :show, id: chat_room.id
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @chat_room_user = @chat_room.chat_room_users.where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: @chat_room)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @post_image = @comment.post_image
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post_image = @comment.post_image
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.required(:comment).permit(:user_id, :post_image_id, :comment)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    @like = current_user.likes.new(like_params)
    @like.save
  end


  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    @like = Like.find_by(id: params[:id])
    @like.destroy
  end

  private
    def like_params
      params.permit(:post_image_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecohabigram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%#= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'ホーム', post_images_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user), class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <!--<p>善良な市民同士で無差別に食欲を煽るSNS</p>-->
            <%#= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <!--<h6 class="text-white mt-2 mb-3">Link</h6>-->
            <ul class="p-0 list-unstyled">
              <li>
                <!--<a href="" title="About" class="text-white-50">会社概要</a>-->
              </li>
              <li>
                <!--<a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>-->
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          <%= link_to "投稿", "#", class: "btn btn-primary" %>
        </li>
        <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
        </li>
      </ul>
    </div>
  </div>
</nav>